name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Ckeckout Repo
          uses: actions/checkout@v4
       

        - name: List And Read Files
          run: |
            echo "welcome! to your first action"
            ls -la
            cat README.md


        - name: Generate Ascii Artwork
          run: cowsay -f dragon "Run for cover , im a Dragon......RAWR" >> dragon.txt

 #       - name: List Files
 #         run: ls

#        - name: Read File
#          run: cat README.md