name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "welcome! to your first action"
        
        - name: List Files
          run: ls


        - name: Read File
          run: cat ReaDME.md