name: Generate ASCII Artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Ckeckout Repo
          uses: actions/checkout@v4
       
        - name: List Files
          run: ls -la

        - name: Executing ascii-script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh



        